### ISSUE TITLE
How to specify different API addresses?

### ISSUE THREAD

**Issue by danyhm** [extremecoders-re/Virtual-File-System-Editor#1]
Hi,

First of all thanks a lot for this project.

I'm trying to get it to work with Winlicense Xbundler. However, since the Xbundler hooks some of the file APIs it's not possible to browse for the files if their names are not known. But, if you know the exact path and name it's possible to extract them by using the "Extract By name" Feature.
How can I specify my own winAPI which I know is not hooked to browse for the files?

**Comment by extremecoders-re** [comment]
NOTE: The precompiled binaries provided are only for 32-bit. Hence you won't be able to use the tool as is on 64 bit executables which I assume your target is.

About the question,
If you know a API which is not hooked by WinLicense, you can use `GetProcAddress` to obtain its address and then call the function through the returned pointer.

The code which does this is
https://github.com/extremecoders-re/Virtual-File-System-Editor/blob/8d59939b641be8c1536fd743bbb89905d970cf3e/vfseditor/hiddendialog.pas#L129-L157

At this point you may be better of writing your own DLL in Pascal/Delphi/C etc and inject that in the running process.

**Comment by danyhm** [comment]
Thanks for the reply,

my target is 32-bit and I wanted to do this using your DLL.

the 4 functions you provided in the DLL don't actually "find" the hidden files.

from the Winlicense Help, it seems they hook the FindNext FindFirst Apis to hide the bundled files. I don't have this problem with Thinapp for example.

I don't know if this is possible to Unhook their hooks since the hooks are installed for the whole process.

any ideas?

**Comment by extremecoders-re** [comment]
> How can I specify my own winAPI which I know is not hooked to browse for the files?

The FindFirstFile / FindNextFile and their variants (eg FindFirstFileExA) are usually used to enumerate all files in a directory. If you know of one which is not hooked you can use that in your DLL. Once you get the names, can then use the Extract by name feature.

**Comment by extremecoders-re** [comment]
> I don't know if this is possible to Unhook their hooks since the hooks are installed for the whole process.

The files are virtualized. Even if the APIs are unhooked it wont return the embedded files as they don't exist on the real file system.

**Comment by extremecoders-re** [comment]
You need to know the real file paths in order to extract them. To know the paths, can consider setting your own hook on CreateFileA or similar.

**Comment by danyhm** [comment]
> > I don't know if this is possible to Unhook their hooks since the hooks are installed for the whole process.
> 
> The files are virtualized. Even if the APIs are unhooked it wont return the embedded files as they don't exist on the real file system.

I was wondering about this as well. so I tested it and it turns out it does return the actual file. the xBundler acts just as a file bundler which also protects and hides them.
